### ISSUE TITLE
Incorrect line number for errors when using imports

### ISSUE THREAD

**Issue by ghost** [acdvorak/intellij-lessc-plugin#1]
When there is an error in in a LESS file that imports other files, the line number given in the error message is not correct. It seems to correspond to the number the line would be if all the imports were concatenated inline before it. 

Eg I put an error on line 7 of a file, and have imported another 53 line file. The error message tells me that it is on line 59 (I'm assuming something is replacing the import statement with the actual contents of the file)

Obviously this makes it more difficult to track down the error.

**Comment by acdvorak** [comment]
This is due to how [lesscss-java](https://github.com/marceloverdijk/lesscss-java), the official LESS compiler for Java (which this plugin uses), handles imports: it merges them all into a single string and compiles the result.  See [LessSource.java, line 147](https://github.com/marceloverdijk/lesscss-java/blob/master/src/main/java/org/lesscss/LessSource.java#L147), which gets fed into [LessCompiler.java, line 302](https://github.com/marceloverdijk/lesscss-java/blob/master/src/main/java/org/lesscss/LessCompiler.java#L302).

I agree that this is really annoying behavior.  It deviates from how the JavaScript version of the LESS compiler works and makes it unnecessarily difficult to pinpoint the source of an error.

My suggestion would be to [file an issue with the lesscss-java project](https://github.com/marceloverdijk/lesscss-java/issues?state=open).  If they decide to fix it, I'll be **_very_** happy to update the plugin to use the new version.

Thanks for reporting this!

**Comment by acdvorak** [comment]
Created an [issue for this bug](https://github.com/marceloverdijk/lesscss-java/issues/6) on the `lesscss-java` project's issue tracker.
