### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by mikenereson** [acdvorak/intellij-lessc-plugin#13]
Updated yesterday to `2.1.1`

No .less will compile. All files give `java.io.IOException`

Downgraded to `2.1.0`, still getting this. No stracktrace presented anywhere.

```
LESS CSS Compiler Error
mixins.less: java.io.IOException: No such file C:\dev\svnlocal\trunk\xxx\src\main\resources\MODULE-INF\web\stylesheets\less\mixins.less
```

These files do exist... Checked windows file permissions. Also tried moving files and creating new files. All give the same error.

**Comment by mikenereson** [comment]
Reverted to `1.9.0`. This works fine. So the bug was introduced after `2012-06-13`

**Comment by acdvorak** [comment]
@ivankolev reported the same problem in #12.  This might be a platform-specific issue (both users are running Windows, whereas I use a Mac).  I'll install IntelliJ IDEA on my Windows box and look into it.

Sorry for the inconvenience, and thanks for reporting this issue!

**Comment by mikenereson** [comment]
Apologies for duplicating issues. Thanks for writing and maintaining this plugin.

**Comment by acdvorak** [comment]
@asual's `LessEngine.compile(File input, boolean compress)` passes `file.getAbsolutePath()` into `StreamResourceLoader.load(String path, String charset)`, which attempts to determine if the path contains a "file:" URI scheme using a regular expression that also matches Windows-style paths (e.g., "C:\some\dir"):

``` java
Matcher m = Pattern.compile("^([\\w]+):(.*)").matcher(path);
if (m.matches()) {
    if (m.group(1).equals(getSchema())) {
        return load(m.group(2), charset);
    }
    throw new IOException("No such file " + path);
}
```

The outer `if` statement returns `true`, but the inner one returns `false` because "C" does not equal "file" (returned by `getSchema()`).

The fix was to simply pass the fully-qualified URL into `LessEngine.compile(URL input, boolean compress)`.  I tested it in Windows and it seems to work properly now.

An updated version of the plugin (2.1.2) containing the bug fix has been uploaded to the JetBrains plugin repository.  It should be available for download in a day or two once the moderators approve it.

Please let me know if you run into any other issues.  Thanks again for taking the time to report this!

**Comment by mikenereson** [comment]
Works. Cheers.

**Comment by ivankolev** [comment]
Good job! Thanks!

2012/10/31 mikenereson notifications@github.com
